### ISSUE TITLE
Including React in deps breaks npm config

### ISSUE THREAD

**Issue by BigAB** [stealjs/system-npm#128]
## Steps to reproduce:

1. Clone this gist repo:
https://gist.github.com/BigAB/f5cb06c8e9ef258875dc2cbfcd8372eb

2. run `npm install`

3. serve `index.html`

You'll get an error in the browser:
```
steal - error loading @config. TypeError: Error loading "package.json!npm" at http://localhost:8000/package.json
moduleName.split is not a function
    at Object.utils.moduleName.parse (http://localhost:8000/node_modules/steal/ext/npm-utils.js:149:33)
    at convertBrowserProperty (http://localhost:8000/node_modules/steal/ext/npm-convert.js:249:43)
    at Object.convertBrowser [as browser] (http://localhost:8000/node_modules/steal/ext/npm-convert.js:239:3)
    at Array.<anonymous> (http://localhost:8000/node_modules/steal/ext/npm.js:68:23)
    at Object.utils.forEach (http://localhost:8000/node_modules/steal/ext/npm-utils.js:56:7)
    at http://localhost:8000/node_modules/steal/ext/npm.js:56:9
    at tryCatchReject (http://localhost:8000/node_modules/steal/steal.js:1183:30)
    at runContinuation1 (http://localhost:8000/node_modules/steal/steal.js:1142:4)
    at Fulfilled.when (http://localhost:8000/node_modules/steal/steal.js:930:4)
    at ContinuationTask.run (http://localhost:8000/node_modules/steal/steal.js:1040:24)
```

...and all the things configured in npm will no longer work.

Seems to have to do with React having this in their package.json:
```
  "browserify": {
    "transform": [
      "loose-envify"
    ]
  },
```
...and steal/system-npm breaks because transform is an array.

**Comment by matthewp** [comment]
Thanks!
