### ISSUE TITLE
system-npm does not work with steal 0.16

### ISSUE THREAD

**Issue by pYr0x** [stealjs/system-npm#144]
update to steal 0.16 cause a error on test http://localhost:8080/test/steal.html?testId=357a8ad5

```
normalizing: Loads npm convention of folder with trailing slash (1, 0, 1)Rerun290342 ms
Died on test #1     at Object.<anonymous> (http://localhost:8080/test/normalize_test.js:207:7)
    at http://localhost:8080/test/normalize_test.js:393:4
    at http://localhost:8080/test/normalize_test.js:393:98
    at doEval (http://localhost:8080/node_modules/steal/steal.js:4931:12)
    at __eval (http://localhost:8080/node_modules/steal/steal.js:4877:7)
    at Loader.exec [as __exec] (http://localhost:8080/node_modules/steal/steal.js:3240:5)
    at load.metadata.execute (http://localhost:8080/node_modules/steal/steal.js:4118:16): Illegal module name "./."@ 290324 ms
Source: 	
TypeError: Illegal module name "./."
    at Loader.$__Object$defineProperty.value (http://localhost:8080/node_modules/steal/steal.js:2748:19)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:4570:44)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:4611:44)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:5220:21)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:5253:21)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:5403:22)
    at Loader.loader.normalize (http://localhost:8080/node_modules/steal/steal.js:5466:36)
    at Loader.System.normalize (http://localhost:8080/npm-extension.js:67:24)
    at Loader.loader.normalize (http://localhost:8080/test/helpers.js:75:20)
    at Object.<anonymous> (http://localhost:8080/test/normalize_test.js:232:9)
Source: at Object. (http://localhost:8080/test/normalize_test.js:207:7) at http://localhost:8080/test/normalize_test.js:393:4 at http://localhost:8080/test/normalize_test.js:393:98 at doEval (http://localhost:8080/node_modules/steal/steal.js:4931:12) at __eval (http://localhost:8080/node_modules/steal/steal.js:4877:7) at Loader.exec [as __exec] (http://localhost:8080/node_modules/steal/steal.js:3240:5) at load.metadata.execute (http://localhost:8080/node_modules/steal/steal.js:4118:16)
```

it seems that the loader.normalize function is not working correctly or is not correctly overwritten with the helper function

**Comment by matthewp** [comment]
Thanks, will take a look this week.

**Comment by pYr0x** [comment]
you can track this on this branch. i updated und added test for the npmAlgorithm
https://github.com/stealjs/system-npm/tree/default-npm-algorithm
