### ISSUE TITLE
How to configure systemjs

### ISSUE THREAD

**Issue by whitecolor** [stealjs/system-npm#36]
If to use with systemjs it not clear how to configure systemjs to load system-npm correctly. Can you ellaborate what configuration should be doen before we can do:

```javascirpt
System.import("package.json!npm").then(function() {
  // Configurations set, you can start importing stuff
});
```
?

I've done:
```javascript
     System.config({
                map: {"npm": "../node_modules/system-npm/npm"
                }
            })
    System.import('package.json!npm')
```
But get the error in browser:

```
Potentially unhandled rejection [3] TypeError: Error loading "package.json!../node_modules/system-npm/npm" at <unknown>
Cannot read property 'default' of undefined
    at http://localhost:7003/node_modules/systemjs/dist/system.js:1:17392
    at O (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:7439)
    at K (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:7071)
    at y.7.y.when (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:10745)
    at v.7.v.run (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:9781)
    at a.3.a._drain (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:1740)
    at 3.a.drain (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:1394)
    at MutationObserver.b (http://localhost:7003/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.js:7:3302)
```

**Comment by matthewp** [comment]
Good point, the easiest way is to use a couple of paths and a wildcard path:

```js
System.config({
  map: {
    "npm": "system-npm/npm",
    "npm-extension": "system-npm/npm-extension"
  },
  paths: {
    "system-npm/*": "node_modules/system-npm/*.js"
  }
});
```

**Comment by matthewp** [comment]
Also you can probably install with jspm (haven't tried this)

```js
jspm install system-npm --save
```

**Comment by justinbmeyer** [comment]
If you are using jspm, you probably don't need system-npm.

**Comment by matthewp** [comment]
jspm is the easiest way to install SystemJS, so you could use jspm just for that purpose and use npm otherwise (then you don't have to have duplicate installs for your node/browser code).

**Comment by matthewp** [comment]
I added a demo folder with an example that uses system-npm with SystemJS.
